name: recipe-manager
base: core24
version: 'dev'
summary: A desktop app for managing a local recipe ebook
description: |
  Recipe Manager is a Flutter desktop app for managing a local collection
  of recipes.
grade: stable
confinement: classic

apps:
  recipe-manager:
    command: recipe_manager

parts:
  recipe-manager:
    plugin: dump
    source: build/linux/x64/release/bundle
