name: recipe-manager-windows-ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get version from pubspec.yaml
        id: version
        shell: bash
        run: |
          VERSION_FULL=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          BUILD_NAME=${VERSION_FULL%%+*}
          echo "version=$BUILD_NAME" >> $GITHUB_OUTPUT

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: dart run flutter_launcher_icons
      - run: flutter test
      - run: flutter build windows --release --no-tree-shake-icons --build-number ${{ github.run_number }}

      - name: Create ZIP archive
        run: Compress-Archive -Path 'build\windows\x64\runner\Release\*' -DestinationPath 'recipe-manager-${{ steps.version.outputs.version }}-windows.zip'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: 'recipe-manager-${{ steps.version.outputs.version }}-windows.zip'
          name: 'recipe-manager-${{ steps.version.outputs.version }}'
          tag_name: ${{ steps.version.outputs.version }}
